name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
          description: 'Log level'
          required: true
          default: 'warning'
          type: choice
          options:
          - info
          - warning
          - debug

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true

      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
          - os: macos-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4

    - name: Set up virtual environment
      shell: bash
      run: python3 -m venv virtualenv

    - name: Install Conan
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          virtualenv/Scripts/activate && pip3 install conan && conan profile detect
        else
          source virtualenv/bin/activate && pip3 install conan && conan profile detect
        fi

    - name: Install NSIS
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          choco install nsis
        fi

    - name: Build project
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          virtualenv/Scripts/activate && cmake -P util/task/package.cmake
        else
          source virtualenv/bin/activate && cmake -P util/task/package.cmake
        fi
      
    - name: Install project
      shell: bash
      run: cmake --install built/Release --config Release

